apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lucas.gregorio@ctiturbo.com.br
    privateKeySecretRef:
      name: letsencrypt-prod-multicloud
    solvers:
    - http01:
        ingress:
          class: nginx